name: Reusable workflow

on:
  workflow_call
  
jobs:
  check:
    name: Check plugin changes
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            kukumo-rest:
              - 'kukumo-plugins/kukumo-rest/**'
